# -*- coding: utf-8 -*-
"""X5_DataMonetize01_data_gen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ipmsMW-OBXybGK5p9jsu8EycMygZLu0o
"""

import pandas as pd
import datetime
import numpy as np
import random

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier

"""Подход к решению задачи по прогнозированию покупок беременных. Тестовое задание к хакатону от Х5. Испольнитель Бочаров А.М. скайп bam271074

Прогнозирование детских покупок можно сделать на основании покупок, которые женщина делает во время беременности. Известно, что в период беременности женщина нуждается в витаминах и фолиевой кислоте. Таким образом если женщина возраста от 16 до 40 лет часто покупает овощи, фрукты, овес, постное мясо, молочные изделия. На основании данной информации можно построить модель, обучить ее выявлять данную закономерность и использовать в работе.
"""

pip list

"""### Версии:

- `numpy`: 1.18.4
- `pandas`: 1.0.3
- `sklearn`: 0.21.3

#сгенерируем датасет и сделаем бинарную классификацию. Если в покупках есть молочные продукты, то 1(покупательница может быть беременной), 0(в покупках нет продуктов, которые обычно покупают беременные)
"""

#let s fix random state
value = 42
random.seed(value)
np.random.seed(value)

clients = pd.Series(['Ann     ', 'Alla    ', 'Chloe   ', 'Dorophy ', 'Emma    ', 'Filona  ', 'Gina    ',\
                     'Hilary  ', 'Ira     ', 'Sophy   '],
                    )
print(clients)

#допустим у нас в магазине следующие продукты

products = pd.Series(['Abritos', 'Bananas', 'Onion', 'Sugar', 'Eris', 'Fries', 'Bread', 'Water', 'Cheese', 'Salo',\
                      'Vodka','Beer','Vine','Sweet','Cigar','Salt','Pepper',\
                     'Milk','Kefir','Iogurt','Cream'],
                       index=['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21'])
print(products)

#сгенерируем список из 20000 элементов, каждая строка записи будет содержать имя покупателя и покупки, которые от сделал
buy_list =[]
buyer_list=[]
flag_list=[]  #списко для записи есть ли молочные продукты или нет
milk_set=set(['Milk','Kefir','Iogurt','Cream','Cheese'])
print(milk_set)
for i in range(20000):
  buyer = ' '.join(clients.sample(1, replace=True))   #выбираем одного клиента из списка всех клиентов
  #buyer = buyer[5:15]
  pokupky = products.sample(3, replace=False)  #выбираем покупки, которые сделал клиент
  for i in range(len(pokupky)):
    flag='negative'
    if pokupky[i] in milk_set:
      flag = 'positive'   #если в покупках есть молоцные продукты то флаг ПОЗИТИВ
      break
  str_buff=' '.join(pokupky)
  buyer_list.append(buyer)
  buy_list.append(str_buff)
  flag_list.append(flag)
print(buy_list)
print(buyer_list)
print(flag_list)

#let s make dataframe
data_df=pd.DataFrame({'Client':buyer_list,'Products':buy_list,'Target':flag_list})
data_df.head(20000)

data_df.to_csv('pokupty20000.csv',index=False)

from google.colab import files
files.download('pokupty20000.csv')